CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."


# Defining model
DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_PATCH_TOKEN = "<vid_patch>"
DEFAULT_VID_START_TOKEN = "<vid_start>"
DEFAULT_VID_END_TOKEN = "<vid_end>"

DEFAULT_POSE_TOKEN = "<human_pose>"
DEFAULT_POSE_PATCH_TOKEN = "<pose_patch>"
DEFAULT_POSE_START_TOKEN = "<pose_start>"
DEFAULT_POSE_END_TOKEN = "<pose_end>"

DEFAULT_OBJECT_TOKEN= "<object>"
DEFAULT_OBJECT_PATCH_TOKEN = "<object_patch>"
DEFAULT_OBJECT_START_TOKEN = "<object_start>"
DEFAULT_OBJECT_END_TOKEN = "<object_end>"